export enum StageEnum {
  MEDICAO = 1,
  PROJETO = 2,
  LANCAMENTO_ORCAMENTO = 3,
  ANALISE_ORCAMENTO = 4,
  APRESENTACAO_PROJETO = 5,
  NEGOCIACAO = 6,
  PAINEL_ELETRICO = 7,
  SEPARACAO_ENTREGA = 8,
  MONTAGEM = 9,
  ASSISTENCIA = 10
}
